---
# These tasks are responsible for copying the latest dev/production code from
# the version control system.


- name: Copy the code from repository
  git: repo={{ repository }} dest=/var/www/html/git/

- name: Creates the index.php file
  template: src=index.php.j2 dest=/var/www/html/index.php

- name: Creates the info.php file
  template: src=info.php dest=/var/www/html/info.php
