---
- hosts: all
  user: root

  tasks:
    - debug: msg="The random password1 is {{ lookup('password', '/tmp/passwordfile1 chars=ascii_letters') }}"
    - debug: msg="The random password2 is {{ lookup('password', '/tmp/passwordfile2 chars=digits') }}"
    - debug: msg="The random password3 is {{ lookup('password', '/tmp/passwordfile3 chars=ascii_letters,digits,hexdigits,punctuation') }}"
