---

- hosts: lb
  user: root

  tasks:
  - name: give users access to multiple databases
    # mysql_user: name={{ item[0] }} priv={{ item[1] }}.*:ALL append_privs=yes password=foo
    debug: msg='name={{ item[0] }} priv={{ item[1] }}.*:ALL append_privs=yes password=foo'
    with_nested:
      - [ 'alice', 'bob' ]
      - [ 'clientdb', 'employeedb', 'providerd']
