---

- hosts: lb
  user: root


  roles:
    - { role: role_with_var, ex_param: "Hello from ex_param for the 1st time"}
    - { role: role_with_var, ex_param: "Hello from ex_param for the 2nd time", in_param1: "This is the value from external" }
